enableGlobalCache: false

enableScripts: false

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

yarnPath: .yarn/releases/yarn-4.0.0-rc.22.git.20221004.hash-c6f7f8b.cjs
